//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具 FreeSql.Generator 生成。
//     运行时版本:3.1.1
//     Website: https://github.com/2881099/FreeSql
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
namespace Id4WebApi
{

	/// <summary>
	/// 门店
	/// </summary>
	[JsonObject(MemberSerialization.OptIn), Table(Name = "bas_store")]
	public partial class BasStore {

		/// <summary>
		/// 门店地址
		/// </summary>
		[JsonProperty, Column(Name = "address", DbType = "varchar(100)")]
		public string Address { get; set; } = string.Empty;

		/// <summary>
		/// 区域代码
		/// </summary>
		[JsonProperty, Column(Name = "area_code", DbType = "varchar(20)")]
		public string AreaCode { get; set; } = string.Empty;

		/// <summary>
		/// 区域名称
		/// </summary>
		[JsonProperty, Column(Name = "area_title", DbType = "varchar(20)")]
		public string AreaTitle { get; set; } = string.Empty;

		/// <summary>
		/// 城市代码
		/// </summary>
		[JsonProperty, Column(Name = "city_code", DbType = "varchar(10)")]
		public string CityCode { get; set; } = string.Empty;

		/// <summary>
		/// 城市名称
		/// </summary>
		[JsonProperty, Column(Name = "city_title", DbType = "varchar(10)")]
		public string CityTitle { get; set; } = string.Empty;

		/// <summary>
		/// 门店代码
		/// </summary>
		[JsonProperty, Column(Name = "code", DbType = "varchar(50)")]
		public string Code { get; set; } = string.Empty;

		/// <summary>
		/// 创建时间
		/// </summary>
		[JsonProperty, Column(Name = "create_time", DbType = "datetime")]
		public DateTime CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[JsonProperty, Column(Name = "create_user", DbType = "varchar(20)")]
		public string CreateUser { get; set; } = string.Empty;

		/// <summary>
		/// 数据有效性：0无效，1有效
		/// </summary>
		[JsonProperty, Column(Name = "data_flag")]
		public int DataFlag { get; set; }

		/// <summary>
		/// 政策描述
		/// </summary>
		[JsonProperty, Column(Name = "description", DbType = "varchar(200)")]
		public string Description { get; set; } = string.Empty;

		/// <summary>
		/// 门店标签
		/// </summary>
		[JsonProperty, Column(Name = "flag", DbType = "varchar(200)")]
		public string Flag { get; set; } = string.Empty;

		/// <summary>
		/// 酒店Guid
		/// </summary>
		[JsonProperty, Column(Name = "hotel_id", DbType = "varchar(36)")]
		public string HotelId { get; set; } = string.Empty;

		/// <summary>
		/// 主键
		/// </summary>
		[JsonProperty, Column(Name = "identity_id", IsIdentity = true)]
		public long IdentityId { get; set; }

		/// <summary>
		/// 门店图片
		/// </summary>
		[JsonProperty, Column(Name = "imgae_url", DbType = "varchar(200)")]
		public string ImgaeUrl { get; set; } = string.Empty;

		/// <summary>
		/// 酒店介绍
		/// </summary>
		[JsonProperty, Column(Name = "introduction", DbType = "varchar(200)")]
		public string Introduction { get; set; } = string.Empty;

		/// <summary>
		/// 是否删除：0未删除，1已删除
		/// </summary>
		[JsonProperty, Column(Name = "is_deleted")]
		public int IsDeleted { get; set; }

		/// <summary>
		/// 维度
		/// </summary>
		[JsonProperty, Column(Name = "latitude", DbType = "decimal(20,15)")]
		public decimal Latitude { get; set; }

		/// <summary>
		/// 门店Logo
		/// </summary>
		[JsonProperty, Column(Name = "logo_url", DbType = "varchar(200)")]
		public string LogoUrl { get; set; } = string.Empty;

		/// <summary>
		/// 经度
		/// </summary>
		[JsonProperty, Column(Name = "longitude", DbType = "decimal(20,15)")]
		public decimal Longitude { get; set; }

		/// <summary>
		/// 门店负责人
		/// </summary>
		[JsonProperty, Column(Name = "person_in_charge", DbType = "varchar(20)")]
		public string PersonInCharge { get; set; } = string.Empty;

		/// <summary>
		/// 门店负责人联系方式
		/// </summary>
		[JsonProperty, Column(Name = "person_in_charge_phone", DbType = "varchar(20)")]
		public string PersonInChargePhone { get; set; } = string.Empty;

		/// <summary>
		/// GUID主键
		/// </summary>
		[JsonProperty, Column(Name = "pid", DbType = "varchar(36)")]
		public string Pid { get; set; } = string.Empty;

		/// <summary>
		/// PMS配置信息
		/// </summary>
		[JsonProperty, Column(Name = "pms_config", DbType = "text")]
		public string PmsConfig { get; set; } = string.Empty;

		/// <summary>
		/// 门店PMSId
		/// </summary>
		[JsonProperty, Column(Name = "pms_id", DbType = "varchar(20)")]
		public string PmsId { get; set; } = string.Empty;

		/// <summary>
		/// PMS类型
		/// </summary>
		[JsonProperty, Column(Name = "pms_type")]
		public int PmsType { get; set; }

		/// <summary>
		/// 省名称
		/// </summary>
		[JsonProperty, Column(Name = "priovince_title", DbType = "varchar(10)")]
		public string PriovinceTitle { get; set; } = string.Empty;

		/// <summary>
		/// 省代码
		/// </summary>
		[JsonProperty, Column(Name = "province_code", DbType = "varchar(10)")]
		public string ProvinceCode { get; set; } = string.Empty;

		/// <summary>
		/// 备注
		/// </summary>
		[JsonProperty, Column(Name = "remark", DbType = "varchar(200)")]
		public string Remark { get; set; } = string.Empty;

		/// <summary>
		/// 房间数
		/// </summary>
		[JsonProperty, Column(Name = "room_num")]
		public int RoomNum { get; set; }

		/// <summary>
		/// 门店星级
		/// </summary>
		[JsonProperty, Column(Name = "star")]
		public int Star { get; set; }

		/// <summary>
		/// 门店电话
		/// </summary>
		[JsonProperty, Column(Name = "telephone", DbType = "varchar(20)")]
		public string Telephone { get; set; } = string.Empty;

		/// <summary>
		/// 门店缩略图
		/// </summary>
		[JsonProperty, Column(Name = "thumbnail_url", DbType = "varchar(200)")]
		public string ThumbnailUrl { get; set; } = string.Empty;

		/// <summary>
		/// 门店名称
		/// </summary>
		[JsonProperty, Column(Name = "tilte", DbType = "varchar(50)")]
		public string Tilte { get; set; } = string.Empty;

		/// <summary>
		/// 更新时间
		/// </summary>
		[JsonProperty, Column(Name = "update_time", DbType = "datetime")]
		public DateTime UpdateTime { get; set; }

		/// <summary>
		/// 更新人
		/// </summary>
		[JsonProperty, Column(Name = "update_user", DbType = "varchar(20)")]
		public string UpdateUser { get; set; } = string.Empty;

		/// <summary>
		/// 版本号
		/// </summary>
		[JsonProperty, Column(Name = "version")]
		public long Version { get; set; }

		/// <summary>
		/// 门店小程序二维码
		/// </summary>
		[JsonProperty, Column(Name = "wechat_applet_qrcode", DbType = "varchar(200)")]
		public string WechatAppletQrcode { get; set; } = string.Empty;

		/// <summary>
		/// 门店公众号二维码
		/// </summary>
		[JsonProperty, Column(Name = "wechat_official_account_qrcode", DbType = "varchar(200)")]
		public string WechatOfficialAccountQrcode { get; set; } = string.Empty;

	}

}
